### ISSUE TITLE
关于record的isBigSize的疑问

### ISSUE THREAD

**Issue by MephistoCC** [pepsikirk/PKShortVideo#13]
if (self.isBigSize) {
        captureSession.sessionPreset = AVCaptureSessionPresetMedium;//360 x 480 小视频一般不会超过此尺寸
    } else {
        captureSession.sessionPreset = AVCaptureSessionPreset1280x720;//720 x 1280 小视频一般不会超过此尺寸
    }
满足isBigSize的情况 摄像头会更模糊。   方便说一下为什么要这么处理吗

**Comment by pepsikirk** [comment]
@MephistoCC 这个是bug……写错了
