### ISSUE TITLE
请问一下，录制的视频上传后支持浏览器的在线播放吗？我直接使用您的sdk录，上传，之后后台返回的链接用webview播放不了，请问和录制有关系吗？

### ISSUE THREAD

**Issue by JsonJieLi** [pepsikirk/PKShortVideo#14]

**Comment by pepsikirk** [comment]
@JsonJieLi 这种情况我建议是用http下载到本地，然后使用 PKFullScreenPlayerView 播放，如果有定制需求可以使用 PKPlayerView 加载在 View 上播放。如果你想验证视频可不可用可以通过自己浏览器下载到本地播放看看。

**Comment by JsonJieLi** [comment]
谢谢回答，视频在本地是可以播放的，只是在线播不了

**Comment by pepsikirk** [comment]
@JsonJieLi 那就不是视频的问题咯，在线用webview播放的方式我也没试过，感觉应该不行，除非是一个网页自带了了播放引擎这样的，像优酷

**Comment by JsonJieLi** [comment]
@pepsikirk 请问demo录制的视频是默认h264编码，mp4格式的吗？因为没看过不懂这两者的相互关系与影响？感谢回答

**Comment by pepsikirk** [comment]
@JsonJieLi 关于编码和封装推荐你看这篇文章，写的很详细 http://www.jianshu.com/p/b61cd0bc2abe
