### ISSUE TITLE
发很多小视频，快速滑动屏幕，有两处崩溃现象

### ISSUE THREAD

**Issue by Aoce** [pepsikirk/PKShortVideo#16]
第一处发生在这里：
![2017-03-10 10 20 40](https://cloud.githubusercontent.com/assets/10444831/23779569/30f995a8-057c-11e7-9f55-48c3c7cbe1b7.png)
第二处发生在这里：
![2017-03-10 10 25 07](https://cloud.githubusercontent.com/assets/10444831/23779588/48bc93ac-057c-11e7-8483-0e1124821a08.png)

应该还有一两处，都是关于内存释放的问题。试了好多种办法，还不能解决，希望大神帮忙看下。

**Comment by chaosVoid** [comment]
顶起，我这里也有这个情况，不是必现，是概率出现。快速滚动时大几率出现。

**Comment by pepsikirk** [comment]
@Aoce @EternalWill PKChatMessagePlayerView 使用的 OpenGL 的实现通过反映目前并不稳定，推荐使用 PKPlayerView ，使用接口完全一致。

**Comment by chaosVoid** [comment]
给予AVPlayer的视频播放有以下缺陷:
1.   资源耗费高，卡顿严重，
2.  之前测试发现部分Android发过来的视频，AVPlayer播放失败(全黑屏)，只有OpenGL实现的能正常。

**Comment by pepsikirk** [comment]
@EternalWill 
1.卡顿严重这个iphone5以上都不太会吧……4s是有点卡
2.播放失败这个你们可以协议好播放的格式码率什么的，固定了一般就没问题吧
OpenGL崩溃的问题我还没有什么头绪，也没什么时间搞定啊……你如果有方案可以pullrequest呢

**Comment by Aoce** [comment]
@pepsikirk 我用6sp 测试demo中的AVPlayer，发很多小视频，滑动后屏幕卡顿还是很严重，做了滚动优化也不行.

**Comment by pepsikirk** [comment]
@Aoce 有那么夸张吗，我的5s我跑demo都不觉得很卡啊……我们项目都是用AVPlayer的呢……

**Comment by chaosVoid** [comment]
@pepsikirk 之前我改过用AVPlayer，5s基本漂移状态，后来又改回OpenGL。想解决OpenGL里的崩溃的问题，但是里面的代码好难读懂。

**Comment by xgfjyw** [comment]
调试后发现CMSampleBufferRef sampleBufferRef = [readerVideoTrackOutput copyNextSampleBuffer]这一句卡死是因为和cancelReading并发调用了。
具体见AVAssetReader.h第204行，对cancelReading方法的注释有一句是：
This method should not be called concurrently with any calls to -[AVAssetReaderOutput copyNextSampleBuffer].

另外processAssert似乎存在竞态问题。例如在PKVideoDecoder.m281行那个usleep还没完的时候主线程可以调用startProcessing，然后self.reader被替换了；原来线程usleep出来后判断self.reader.status可能还是AVAssetReaderStatusReading，导致原来循环不能正常退出。需要一种机制来保证原来那个while正常退出。

**Comment by pepsikirk** [comment]
@xgfjyw 不错的思路，你可以提交一个pull request试试！

**Comment by xgfjyw** [comment]
@pepsikirk 已经提了，你去检查一下有没有问题

**Comment by pepsikirk** [comment]
@xgfjyw 已经看到了，抱歉之前的pull request没看到

**Comment by pepsikirk** [comment]
@xgfjyw 我根据你的Pull Request提交了新的代码，经过测试实际起效的代码只有 cancelProcessing 方法调用时不直接 [self.reader cancelReading]; ，你可以看看
