### ISSUE TITLE
支持online video

### ISSUE THREAD

**Issue by jay-zhu** [pepsikirk/PKShortVideo#2]
现在如果换成online video 的url, 会显示空白...
AVAssetReader 不支持remote url asset. 
请问,有什么好的方法支持播放远程video呢?

**Comment by pepsikirk** [comment]
@jay-zhu 你好，想要支持远程播放不建议使用PKShortVideo，PKShortVideo的播放主要还是针对于聊天之类的瀑布流界面的播放实现。
我建议你可以直接使用AVPlayer或者是使用Bilibili开源的ijkplayer，谢谢
