### ISSUE TITLE
难道就我一个人发现在android上播放的时候视频被逆时针旋转90度吗？

### ISSUE THREAD

**Issue by hongzhewudi** [pepsikirk/PKShortVideo#21]
<img width="353" alt="qq20170815-163913 2x" src="https://user-images.githubusercontent.com/9473584/29312834-c2c53bb0-81e9-11e7-81ed-c2613a8e48cf.png">
这个视频录制出来是640*480，但是在安卓上播放就被逆时针旋转了90度，请问作者这个是什么原因？

**Comment by hongzhewudi** [comment]
那个H.264 480*640是什么原因？为什么还颠倒了

**Comment by pepsikirk** [comment]
@hongzhewudi 安卓旋转是因为安卓的播放器没有根据视频的角度旋转信息进行旋转

**Comment by hongzhewudi** [comment]
那请问一下，我该如何做才能将这视频录制将角度转过来，直接拿给安卓让他不用考虑角度旋转信息而直接播放？

**Comment by pepsikirk** [comment]
@hongzhewudi 这个就比较麻烦了，因为你去掉角度信息，视频还是反转的，你需要对视频进行反转，我并没有提供这样的api

**Comment by hongzhewudi** [comment]
请问大师可以有解决方案吗？我项目要上线了，测试测出来这个bug，改不掉了，纠缠了好几天了

**Comment by hongzhewudi** [comment]
我们项目安卓使用的是GSYVideoPlayer这个框架，这个框架读到的录制视频是反的，但是安卓自己录制的视频是正确的方向，郁闷呀

**Comment by hongzhewudi** [comment]
https://zh-files.oss-cn-qingdao.aliyuncs.com/20170808223928mJ1P3n57.mp4就是这个视频？请问我现在还有办法吗？

**Comment by pepsikirk** [comment]
@hongzhewudi 我看了GSYVideoPlayer是支持角度信息的，估计是你们安卓开发的问题吧
