### ISSUE TITLE
在iPhone 4跟5（iOS 7.x）上会崩溃

### ISSUE THREAD

**Issue by mofashy** [pepsikirk/PKShortVideo#4]
你好，我发现在iPhone 4跟5（iOS 7.x）上会崩溃（[AVCaptureVideoDataOutput _AVCaptureVideoDataOutput_VideoDataBecameReady]），在dismiss之前将previewLayer remove掉就可以了。希望有点帮助。

``` objc
AVCaptureVideoPreviewLayer *previewLayer = [self.recorder previewLayer];
...
_previewLayer = previewLayer;
```

``` objc
[_previewLayer removeFromSuperlayer];
[self dismissViewControllerAnimated:YES completion:NULL];
```

**Comment by pepsikirk** [comment]
你好@mofashy ，之前的版本使用的 JSQMessagesViewController 并不支持 iOS 7，我现在已经修改支持，并且解决了你说的这个问题，谢谢。

**Comment by pepsikirk** [comment]
你好@mofashy ，之前的版本使用的 JSQMessagesViewController 并不支持 iOS 7，我现在已经修改支持，并且解决了你说的这个问题，谢谢。
