### ISSUE TITLE
从后台进入前台后，程序崩溃

### ISSUE THREAD

**Issue by xuzhenhao** [pepsikirk/PKShortVideo#6]
进入视频录制画面，按home退到后台，之后再进入，点击按住录，程序崩溃。

**Comment by pepsikirk** [comment]
@xuzhenhao 确实有这个问题，已经知道原因了，晚点会更新个新版本解决

**Comment by pepsikirk** [comment]
这个问题已经解决了 @xuzhenhao ，谢谢
