### ISSUE TITLE
关于小视频和录制语音、播放语音的冲突

### ISSUE THREAD

**Issue by eapinZhang** [pepsikirk/PKShortVideo#8]
您好：
因为现在在Tableview上存在小视频的cell和播放录音的cell，如果两者同时存在的话，点击按钮播放录音会报这个[AVAudioSession setActive:withOptions:error:]: Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session，想请问一下有没有什么办法可以结局

**Comment by pepsikirk** [comment]
@eapinZhang 你可以看看http://stackoverflow.com/questions/24114323/ios8-avaudiosession-setactive-error，我们是可以同时播放语音和小视频的
