### ISSUE TITLE
之前录制的小视频再次运行程序就没有声音了

### ISSUE THREAD

**Issue by HaiFeiExplorer** [pepsikirk/PKShortVideo#9]
具体描述为，如果是运行完直接播放该视频是正常的，如果杀死程序，再次运行，之前录制的小视频就没有声音（播放画面是正常的），如果重新录制新的小视频，可以正常播放，之前录制的也可以，

**Comment by pepsikirk** [comment]
@Lisa1900 你打开静音模式，是有声音的，具体原因不清楚，录制的时候静音模式有声音，重新进入静音模式没声音，这个还需要查看下

**Comment by HaiFeiExplorer** [comment]
这个后来设置  AVAudioSession *audioSession = [AVAudioSession sharedInstance];
    NSError *err = nil;
    [audioSession setCategory :AVAudioSessionCategoryPlayback error:&err]; 这样设置之后就可以了，其他的解决方案暂时还没有！！

**Comment by pepsikirk** [comment]
@Lisa1900 原来是这样啊，音频设置的问题，谢谢
